export const ProductsTypes = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCTS_PENDING: 'GET_PRODUCTS_PENDING',
  GET_PRODUCTS_FULFILLED: 'GET_PRODUCTS_FULFILLED',
  GET_PRODUCTS_REJECTED: 'GET_PRODUCTS_REJECTED',

  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_PRODUCT_PENDING: 'ADD_PRODUCT_PENDING',
  ADD_PRODUCT_FULFILLED: 'ADD_PRODUCT_FULFILLED',
  ADD_PRODUCT_REJECTED: 'ADD_PRODUCT_REJECTED',

  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_PENDING: 'UPDATE_PRODUCT_PENDING',
  UPDATE_PRODUCT_FULFILLED: 'UPDATE_PRODUCT_FULFILLED',
  UPDATE_PRODUCT_REJECTED: 'UPDATE_PRODUCT_REJECTED',

  DELETE_PRODUCT: 'DELETE_PRODUCT',
  DELETE_PRODUCT_PENDING: 'DELETE_PRODUCT_PENDING',
  DELETE_PRODUCT_FULFILLED: 'DELETE_PRODUCT_FULFILLED',
  DELETE_PRODUCT_REJECTED: 'DELETE_PRODUCT_REJECTED',
}